apiVersion: v1
kind: Pod
metadata:
  namespace: kube-public
  labels:
    run: kubeview
  name: kubeview
spec:
  containers:
  - image: mjbright/kubeview:0.1
    name: kubeview
    imagePullPolicy: Never
  dnsPolicy: ClusterFirst
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  namespace: kube-public
  labels:
    run: kubeview
  name: kubeview
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: kubeview
